CLASS zcl_tf_prelim_billing_ref_docs DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.

    CLASS-METHODS get_ref_docs
      FOR TABLE FUNCTION ZTF_PRELIM_BILLING_REF_DOCS.
    CLASS-METHODS get_projects
      FOR TABLE FUNCTION ZI_PRELIM_BILLING_PROJECTS.
    CLASS-METHODS get_projects_bd
      FOR TABLE FUNCTION ZI_BILLING_DOC_PROJECTS.
      "AMDP OPTIONS CDS SESSION CLIENT CURRENT